version: '3.8'

services:
  emulator:
    container_name: "servicebus-emulator"
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    volumes:
      - emulatordata:/config.json
    ports:
      - "5672:5672"
    environment:
      SQL_SERVER: sqledge
      MSSQL_SA_PASSWORD: "P@55w0rd"
      ACCEPT_EULA:  "Y"
    depends_on:
      - sqledge
    networks:
      sb-emulator:
        aliases:
          - "sb-emulator"

  sqledge:
    container_name: "sqledge"
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "P@55w0rd"
    networks:
      sb-emulator:
        aliases:
          - "sqledge"

networks:
  sb-emulator:

volumes:
  emulatordata:
